version: "3"

services:
  sr-queue:
    build: ./sr-queue
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: "true"
      TOPICS: carrier-out,carrier-in,vendor-out,vendor-in
    networks:
      - carrier-tier
      - vendor-tier
      - internal-tier

networks:
  carrier-tier:
  vendor-tier:
  internal-tier:
